apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-fdjzfoss
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-fdjzfoss:7923426b8952f3117fabebd83c5467e0b6ef827d@sha256:2450c04edc68d25da64051d670c628253558c29ef3cd7c3958cc076a4de367a7
          name: container-image
